export enum JOIN_REQUEST_STATUS {
    ACCEPTED = "ACCEPTED",
    USER = "USER"
}

export enum CLUB_ROLE  {
    OWNER = "OWNER",
    OFFICER = "OFFICER",
    MEMBER = "MEMBER"
}

export enum APP_ROLE  {
    ADMIN = "ADMIN",
    MOD = "MOD",
    MEMBER = "MEMBER"
}

export enum CLUB_TAGS {
    SPORTS = "SPORTS",
    MUSIC = "MUSIC",
    THEATER = "THEATER",
    TECHNOLOGY = "TEHNOLOGY",
    LEADERSHIP = "LEADERSHIP",
    FRATERNITY = "FRATERNITY",
    SORORITY = "SORORITY",
    ART = "ART",
    FILM = "FILM",
    COOKING = "COOKING",
    VOLUNTEERING = "VOLUNTEERING",
    GAMING = "GAMING",
    CULTURE = "CULTURE",
    LANGUAGE = "LANGUAGE",
    SCIENCE = "SCIENCE",
    POLITICS = "POLITICS",
    SPIRITUAL = "SPIRITUAL",
    BAKING = "BAKING",
    MATH = "MATH",
    ANIMALS = "ANIMALS"
}