export enum JOIN_REQUEST_STATUS {
    ACCEPTED = "ACCEPTED",
    PENDING = "PENDING",
    DENIED = "DENIED"
}

export enum CLUB_ROLE {
    OWNER = "OWNER",
    OFFICER = "OFFICER",
    MEMBER = "MEMBER",
    NONMEMBER = "NONMEMBER"
}

export enum APP_ROLE {
    ADMIN = "ADMIN",
    MOD = "MOD",
    MEMBER = "MEMBER"
}

export enum CLUB_TAGS {
    SPORTS = "SPORTS",
    MUSIC = "MUSIC",
    THEATER = "THEATER",
    TECHNOLOGY = "TEHNOLOGY",
    LEADERSHIP = "LEADERSHIP",
    FRATERNITY = "FRATERNITY",
    SORORITY = "SORORITY",
    ART = "ART",
    FILM = "FILM",
    COOKING = "COOKING",
    VOLUNTEERING = "VOLUNTEERING",
    GAMING = "GAMING",
    CULTURE = "CULTURE",
    LANGUAGE = "LANGUAGE",
    SCIENCE = "SCIENCE",
    POLITICS = "POLITICS",
    SPIRITUAL = "SPIRITUAL",
    BAKING = "BAKING",
    MATH = "MATH",
    ANIMALS = "ANIMALS"
}

export enum PERMISSIONS {
    ADD_EDIT_EVENTS = "ADD_EDIT_EVENTS",
    ADD_ANNOUNCEMENTS = "ADD_ANNOUNCEMENTS",
    MANAGE_APPLICATIONS = "MANAGE_APPLICATIONS",
    MANAGE_MEMBERS = "MANAGE_MEMBERS",
    MANAGE_ROLES = "MANAGE_ROLES"
}
